apply plugin: 'com.android.application'

android {
    compileSdkVersion 37
    defaultConfig {
        applicationId "com.ridhoae303.app"
        minSdkVersion 23
        targetSdkVersion 37
        versionCode 4
        versionName "1.0.4"

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
    }
    buildTypes {
        release {
            debuggable false
            jniDebuggable false
            shrinkResources true
            minifyEnabled true

            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
        debug {
            shrinkResources false
            minifyEnabled false
        }
    }
    externalNativeBuild {
        ndkBuild {
            path file('src/main/jni/Android.mk')
        }
    }
    namespace 'com.ridhoae303.app'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
}
